"""drop email_generations table

Revision ID: 1a97b55e83dc
Revises: c0a32599c033
Create Date: 2026-01-27 16:44:32.887772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a97b55e83dc'
down_revision: Union[str, Sequence[str], None] = 'c0a32599c033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_generations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError(
    "Irreversible migration: dropped table 'my_table'"
    )
    # ### end Alembic commands ###
